/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/observability/pkg/apis/sink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterLogSinks implements ClusterLogSinkInterface
type FakeClusterLogSinks struct {
	Fake *FakeObservabilityV1alpha1
	ns   string
}

var clusterlogsinksResource = schema.GroupVersionResource{Group: "observability.knative.dev", Version: "v1alpha1", Resource: "clusterlogsinks"}

var clusterlogsinksKind = schema.GroupVersionKind{Group: "observability.knative.dev", Version: "v1alpha1", Kind: "ClusterLogSink"}

// Get takes name of the clusterLogSink, and returns the corresponding clusterLogSink object, and an error if there is any.
func (c *FakeClusterLogSinks) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterLogSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterlogsinksResource, c.ns, name), &v1alpha1.ClusterLogSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterLogSink), err
}

// List takes label and field selectors, and returns the list of ClusterLogSinks that match those selectors.
func (c *FakeClusterLogSinks) List(opts v1.ListOptions) (result *v1alpha1.ClusterLogSinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterlogsinksResource, clusterlogsinksKind, c.ns, opts), &v1alpha1.ClusterLogSinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterLogSinkList{ListMeta: obj.(*v1alpha1.ClusterLogSinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterLogSinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterLogSinks.
func (c *FakeClusterLogSinks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterlogsinksResource, c.ns, opts))

}

// Create takes the representation of a clusterLogSink and creates it.  Returns the server's representation of the clusterLogSink, and an error, if there is any.
func (c *FakeClusterLogSinks) Create(clusterLogSink *v1alpha1.ClusterLogSink) (result *v1alpha1.ClusterLogSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterlogsinksResource, c.ns, clusterLogSink), &v1alpha1.ClusterLogSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterLogSink), err
}

// Update takes the representation of a clusterLogSink and updates it. Returns the server's representation of the clusterLogSink, and an error, if there is any.
func (c *FakeClusterLogSinks) Update(clusterLogSink *v1alpha1.ClusterLogSink) (result *v1alpha1.ClusterLogSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterlogsinksResource, c.ns, clusterLogSink), &v1alpha1.ClusterLogSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterLogSink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterLogSinks) UpdateStatus(clusterLogSink *v1alpha1.ClusterLogSink) (*v1alpha1.ClusterLogSink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterlogsinksResource, "status", c.ns, clusterLogSink), &v1alpha1.ClusterLogSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterLogSink), err
}

// Delete takes name of the clusterLogSink and deletes it. Returns an error if one occurs.
func (c *FakeClusterLogSinks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterlogsinksResource, c.ns, name), &v1alpha1.ClusterLogSink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterLogSinks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterlogsinksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterLogSinkList{})
	return err
}

// Patch applies the patch and returns the patched clusterLogSink.
func (c *FakeClusterLogSinks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterLogSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterlogsinksResource, c.ns, name, data, subresources...), &v1alpha1.ClusterLogSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterLogSink), err
}
