/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/knative/observability/pkg/apis/sink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterMetricSinks implements ClusterMetricSinkInterface
type FakeClusterMetricSinks struct {
	Fake *FakeObservabilityV1alpha1
	ns   string
}

var clustermetricsinksResource = schema.GroupVersionResource{Group: "observability.knative.dev", Version: "v1alpha1", Resource: "clustermetricsinks"}

var clustermetricsinksKind = schema.GroupVersionKind{Group: "observability.knative.dev", Version: "v1alpha1", Kind: "ClusterMetricSink"}

// Get takes name of the clusterMetricSink, and returns the corresponding clusterMetricSink object, and an error if there is any.
func (c *FakeClusterMetricSinks) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterMetricSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustermetricsinksResource, c.ns, name), &v1alpha1.ClusterMetricSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMetricSink), err
}

// List takes label and field selectors, and returns the list of ClusterMetricSinks that match those selectors.
func (c *FakeClusterMetricSinks) List(opts v1.ListOptions) (result *v1alpha1.ClusterMetricSinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustermetricsinksResource, clustermetricsinksKind, c.ns, opts), &v1alpha1.ClusterMetricSinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterMetricSinkList{ListMeta: obj.(*v1alpha1.ClusterMetricSinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterMetricSinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterMetricSinks.
func (c *FakeClusterMetricSinks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustermetricsinksResource, c.ns, opts))

}

// Create takes the representation of a clusterMetricSink and creates it.  Returns the server's representation of the clusterMetricSink, and an error, if there is any.
func (c *FakeClusterMetricSinks) Create(clusterMetricSink *v1alpha1.ClusterMetricSink) (result *v1alpha1.ClusterMetricSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustermetricsinksResource, c.ns, clusterMetricSink), &v1alpha1.ClusterMetricSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMetricSink), err
}

// Update takes the representation of a clusterMetricSink and updates it. Returns the server's representation of the clusterMetricSink, and an error, if there is any.
func (c *FakeClusterMetricSinks) Update(clusterMetricSink *v1alpha1.ClusterMetricSink) (result *v1alpha1.ClusterMetricSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustermetricsinksResource, c.ns, clusterMetricSink), &v1alpha1.ClusterMetricSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMetricSink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterMetricSinks) UpdateStatus(clusterMetricSink *v1alpha1.ClusterMetricSink) (*v1alpha1.ClusterMetricSink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustermetricsinksResource, "status", c.ns, clusterMetricSink), &v1alpha1.ClusterMetricSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMetricSink), err
}

// Delete takes name of the clusterMetricSink and deletes it. Returns an error if one occurs.
func (c *FakeClusterMetricSinks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustermetricsinksResource, c.ns, name), &v1alpha1.ClusterMetricSink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterMetricSinks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustermetricsinksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterMetricSinkList{})
	return err
}

// Patch applies the patch and returns the patched clusterMetricSink.
func (c *FakeClusterMetricSinks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterMetricSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustermetricsinksResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterMetricSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterMetricSink), err
}
