kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-generator
  namespace: knative-observability
  labels:
    metrics: "true"
    logs: "true"
    safeToDelete: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - cert-generator
