# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sink-controller
rules:
# The sink-controller needs to patch the configmap for fluent-bit
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"] # TODO: Do we need watch?
# The sink-controller needs to be able to delete the fluent-bit pods
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["deletecollection"]
# The sink-controller needs to be able to watch logsinks and clusterlogsinks
- apiGroups: ["observability.knative.dev"]
  resources: ["logsinks", "clusterlogsinks"]
  verbs: ["get", "list", "watch"]
