# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-controller
  namespace: knative-observability
  labels:
    app: event-controller
    logs: "true"
    safeToDelete: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-controller
  template:
    metadata:
      labels:
        app: event-controller
    spec:
      serviceAccountName: event-controller
      containers:
      - name: event-controller
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: github.com/knative/observability/cmd/event-controller
        imagePullPolicy: IfNotPresent
        env:
          - name: FORWARDER_HOST
            value: fluent-bit.knative-observability.svc.cluster.local
