/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	sinkv1alpha1 "github.com/knative/observability/pkg/apis/sink/v1alpha1"
	versioned "github.com/knative/observability/pkg/client/clientset/versioned"
	internalinterfaces "github.com/knative/observability/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/knative/observability/pkg/client/listers/sink/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterMetricSinkInformer provides access to a shared informer and lister for
// ClusterMetricSinks.
type ClusterMetricSinkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterMetricSinkLister
}

type clusterMetricSinkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterMetricSinkInformer constructs a new informer for ClusterMetricSink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterMetricSinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterMetricSinkInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterMetricSinkInformer constructs a new informer for ClusterMetricSink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterMetricSinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ObservabilityV1alpha1().ClusterMetricSinks(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ObservabilityV1alpha1().ClusterMetricSinks(namespace).Watch(options)
			},
		},
		&sinkv1alpha1.ClusterMetricSink{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterMetricSinkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterMetricSinkInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterMetricSinkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sinkv1alpha1.ClusterMetricSink{}, f.defaultInformer)
}

func (f *clusterMetricSinkInformer) Lister() v1alpha1.ClusterMetricSinkLister {
	return v1alpha1.NewClusterMetricSinkLister(f.Informer().GetIndexer())
}
