/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/knative/observability/pkg/apis/sink/v1alpha1"
	scheme "github.com/knative/observability/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterMetricSinksGetter has a method to return a ClusterMetricSinkInterface.
// A group's client should implement this interface.
type ClusterMetricSinksGetter interface {
	ClusterMetricSinks(namespace string) ClusterMetricSinkInterface
}

// ClusterMetricSinkInterface has methods to work with ClusterMetricSink resources.
type ClusterMetricSinkInterface interface {
	Create(*v1alpha1.ClusterMetricSink) (*v1alpha1.ClusterMetricSink, error)
	Update(*v1alpha1.ClusterMetricSink) (*v1alpha1.ClusterMetricSink, error)
	UpdateStatus(*v1alpha1.ClusterMetricSink) (*v1alpha1.ClusterMetricSink, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterMetricSink, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterMetricSinkList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterMetricSink, err error)
	ClusterMetricSinkExpansion
}

// clusterMetricSinks implements ClusterMetricSinkInterface
type clusterMetricSinks struct {
	client rest.Interface
	ns     string
}

// newClusterMetricSinks returns a ClusterMetricSinks
func newClusterMetricSinks(c *ObservabilityV1alpha1Client, namespace string) *clusterMetricSinks {
	return &clusterMetricSinks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterMetricSink, and returns the corresponding clusterMetricSink object, and an error if there is any.
func (c *clusterMetricSinks) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterMetricSink, err error) {
	result = &v1alpha1.ClusterMetricSink{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterMetricSinks that match those selectors.
func (c *clusterMetricSinks) List(opts v1.ListOptions) (result *v1alpha1.ClusterMetricSinkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterMetricSinkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterMetricSinks.
func (c *clusterMetricSinks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterMetricSink and creates it.  Returns the server's representation of the clusterMetricSink, and an error, if there is any.
func (c *clusterMetricSinks) Create(clusterMetricSink *v1alpha1.ClusterMetricSink) (result *v1alpha1.ClusterMetricSink, err error) {
	result = &v1alpha1.ClusterMetricSink{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		Body(clusterMetricSink).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterMetricSink and updates it. Returns the server's representation of the clusterMetricSink, and an error, if there is any.
func (c *clusterMetricSinks) Update(clusterMetricSink *v1alpha1.ClusterMetricSink) (result *v1alpha1.ClusterMetricSink, err error) {
	result = &v1alpha1.ClusterMetricSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		Name(clusterMetricSink.Name).
		Body(clusterMetricSink).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterMetricSinks) UpdateStatus(clusterMetricSink *v1alpha1.ClusterMetricSink) (result *v1alpha1.ClusterMetricSink, err error) {
	result = &v1alpha1.ClusterMetricSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		Name(clusterMetricSink.Name).
		SubResource("status").
		Body(clusterMetricSink).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterMetricSink and deletes it. Returns an error if one occurs.
func (c *clusterMetricSinks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterMetricSinks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustermetricsinks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterMetricSink.
func (c *clusterMetricSinks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterMetricSink, err error) {
	result = &v1alpha1.ClusterMetricSink{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustermetricsinks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
