/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/knative/observability/pkg/apis/sink/v1alpha1"
	scheme "github.com/knative/observability/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LogSinksGetter has a method to return a LogSinkInterface.
// A group's client should implement this interface.
type LogSinksGetter interface {
	LogSinks(namespace string) LogSinkInterface
}

// LogSinkInterface has methods to work with LogSink resources.
type LogSinkInterface interface {
	Create(*v1alpha1.LogSink) (*v1alpha1.LogSink, error)
	Update(*v1alpha1.LogSink) (*v1alpha1.LogSink, error)
	UpdateStatus(*v1alpha1.LogSink) (*v1alpha1.LogSink, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.LogSink, error)
	List(opts v1.ListOptions) (*v1alpha1.LogSinkList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LogSink, err error)
	LogSinkExpansion
}

// logSinks implements LogSinkInterface
type logSinks struct {
	client rest.Interface
	ns     string
}

// newLogSinks returns a LogSinks
func newLogSinks(c *ObservabilityV1alpha1Client, namespace string) *logSinks {
	return &logSinks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the logSink, and returns the corresponding logSink object, and an error if there is any.
func (c *logSinks) Get(name string, options v1.GetOptions) (result *v1alpha1.LogSink, err error) {
	result = &v1alpha1.LogSink{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logsinks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LogSinks that match those selectors.
func (c *logSinks) List(opts v1.ListOptions) (result *v1alpha1.LogSinkList, err error) {
	result = &v1alpha1.LogSinkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested logSinks.
func (c *logSinks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("logsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a logSink and creates it.  Returns the server's representation of the logSink, and an error, if there is any.
func (c *logSinks) Create(logSink *v1alpha1.LogSink) (result *v1alpha1.LogSink, err error) {
	result = &v1alpha1.LogSink{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("logsinks").
		Body(logSink).
		Do().
		Into(result)
	return
}

// Update takes the representation of a logSink and updates it. Returns the server's representation of the logSink, and an error, if there is any.
func (c *logSinks) Update(logSink *v1alpha1.LogSink) (result *v1alpha1.LogSink, err error) {
	result = &v1alpha1.LogSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logsinks").
		Name(logSink.Name).
		Body(logSink).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *logSinks) UpdateStatus(logSink *v1alpha1.LogSink) (result *v1alpha1.LogSink, err error) {
	result = &v1alpha1.LogSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logsinks").
		Name(logSink.Name).
		SubResource("status").
		Body(logSink).
		Do().
		Into(result)
	return
}

// Delete takes name of the logSink and deletes it. Returns an error if one occurs.
func (c *logSinks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logsinks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *logSinks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logsinks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched logSink.
func (c *logSinks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.LogSink, err error) {
	result = &v1alpha1.LogSink{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("logsinks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
