// +build e2e

/*
Copyright 2018 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package e2e

import (
	"flag"
	"os"
	"testing"

	"github.com/knative/pkg/test"
	"github.com/knative/pkg/test/logging"
	corev1 "k8s.io/api/core/v1"
	kuberrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"k8s.io/client-go/tools/clientcmd"

	oversioned "github.com/knative/observability/pkg/client/clientset/versioned"
	"github.com/knative/observability/pkg/client/clientset/versioned/typed/sink/v1alpha1"
)

// TestMain is called by the test binary generated by "go test", and is
// responsible for setting up and tearing down the testing environment, namely
// the test namespace.
func TestMain(m *testing.M) {
	flag.Parse()
	logging.InitializeLogger(test.Flags.LogVerbose)
	logger := logging.GetContextLogger("TestSetup")
	flag.Set("alsologtostderr", "true")
	if test.Flags.EmitMetrics {
		logging.InitializeMetricExporter()
	}

	clients := setup(logger)
	test.CleanupOnInterrupt(func() { teardownNamespace(clients, logger) }, logger)
	var code int

	defer func() {
		// Cleanup namespace
		teardownNamespace(clients, logger)
		// Exit with m.Run exit code
		os.Exit(code)
	}()

	code = m.Run()
}

type clients struct {
	kubeClient *test.KubeClient
	sinkClient sinkClient
}

const observabilityTestNamespace = "observability-tests"

func teardownNamespace(clients *clients, logger *logging.BaseLogger) {
	logger.Infof("Deleting namespace %q", observabilityTestNamespace)

	err := clients.kubeClient.Kube.CoreV1().Namespaces().Delete(
		observabilityTestNamespace,
		&metav1.DeleteOptions{},
	)
	if err != nil && !kuberrors.IsNotFound(err) {
		logger.Fatalf("Error deleting namespace %q: %v", observabilityTestNamespace, err)
	}
}

func clusterNodes(client *test.KubeClient) (*corev1.NodeList, error) {
	return client.Kube.CoreV1().Nodes().List(metav1.ListOptions{})
}

func setup(logger *logging.BaseLogger) *clients {
	clients, err := newClients()
	if err != nil {
		logger.Fatalf("Error creating newClients: %v", err)
	}

	// Ensure the test namespace exists, by trying to create it and ignoring
	// already-exists errors.
	if _, err := clients.kubeClient.Kube.CoreV1().Namespaces().Create(
		&corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name: observabilityTestNamespace,
			},
		},
	); err == nil {
		logger.Infof("Created namespace %q", observabilityTestNamespace)
	} else if kuberrors.IsAlreadyExists(err) {
		logger.Infof("Namespace %q already exists", observabilityTestNamespace)
	} else {
		logger.Fatalf("Error creating namespace %q: %v", observabilityTestNamespace, err)
	}
	return clients
}

func newClients() (*clients, error) {
	configPath := test.Flags.Kubeconfig
	namespace := observabilityTestNamespace
	clusterName := test.Flags.Cluster

	overrides := clientcmd.ConfigOverrides{}
	// Override the cluster name if provided.
	if clusterName != "" {
		overrides.Context.Cluster = clusterName
	}

	kubeClient, err := test.NewKubeClient(configPath, clusterName)
	if err != nil {
		return nil, err
	}

	cfg, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{
			ExplicitPath: configPath,
		},
		&overrides,
	).ClientConfig()
	if err != nil {
		return nil, err
	}

	sc, err := oversioned.NewForConfig(cfg)
	if err != nil {
		return nil, err
	}

	return &clients{
		kubeClient: kubeClient,
		sinkClient: sinkClient{
			LogSink:        sc.Observability().LogSinks(namespace),
			ClusterLogSink: sc.Observability().ClusterLogSinks(namespace),
		},
	}, nil
}

type sinkClient struct {
	LogSink        v1alpha1.LogSinkInterface
	ClusterLogSink v1alpha1.ClusterLogSinkInterface
}
